### Create a cart
POST http://localhost:3000/cart
Content-Type: application/json

{
  "sessionId": " ",
  "userId": "6820dd2924d4639ab3d8e17f",
  "items": [ ],
  "status": "active",
  "total": 0,
  "vat": 7
}

### Get a cart by userID
GET http://localhost:3000/cart/:userId

### Add item to cartID
POST http://localhost:3000/cart/:cartId/items
Content-Type: application/json

{
  "productId": "681dd534655b54e321a84654",
  "selectedSize": "l",
  "selectedColor": "white",
  "selectedImage": "src/assets/images/Products/shirt/espresso/espresso-shirt-white-front.p…",
  "quantity": 1,
  "unitPrice": 499
}

### Delete an cart-item and update cart total price
DELETE http://localhost:3000/cart/items/:itemId

### Get a populated cart
GET http://localhost:3000/cart/populated/:userId

### Update color'item
PATCH http://localhost:3000/cart/:cartId/items/:itemId/color
Content-Type: application/json

{
  "selectedColor": "blue"
}

### Update size'item
PATCH http://localhost:3000/cart/:cartId/items/:itemId/size
Content-Type: application/json

{
  "selectedSize": "m"
}

### Update quantity'item
PATCH http://localhost:3000/cart/:cartId/items/:itemId/quantity
Content-Type: application/json

{
  "quantity": 3
}

### Update cart item details by itemId (color, size, quantity)
PATCH http://localhost:3000/cart/items/:itemId
Content-Type: application/json

{
    "selectedColor": "black",
    "selectedSize": "m",
    "quantity": 2
}