
### Post an order
POST http://localhost:3000/order
Content-Type: application/json

{
  "userId": "644f1e58f9f8b915d5c7d9a1",
  "items": [
  {
    "productId": "644f1e58f9f8b915d5c7d345",
    "quantity": 5,
    "unitPrice": 499,
    "selectedSize": "s",
    "selectedColor": "black",
    "selectedImage": "test"
  },
  {
    "productId": "644f1e58f9f8b915d5c7d123",
    "quantity": 5,
    "unitPrice": 499,
    "selectedSize": "s",
    "selectedColor": "black",
    "selectedImage": "test"
  }
],
  "total": 40
}



### Get a specific order (by object ID)
GET http://localhost:3000/order/68220c6643db794d597c5b03

### Patch order'status (by object ID)
PATCH  http://localhost:6000/order/681b33538d95bd1c8e098fc4
Content-Type: application/json

{
  "status":"paid"
}

### Delete CartItem (by cartID and cartItem ID)
DELETE  http://localhost:3000/cart/6821de7c9f107d6ad0c88358/item/6821df809f107d6ad0c88368